trigger:
- master
jobs:
 - job: Build
   pool:
     name: 'Azure Pipelines'
     demands: AGENT_KIND -equals Hosted Agent
   steps:
   - task: DotNetCoreInstaller@0
     inputs:
       packageType: 'sdk'
       version: '2.2.401'
   - script: dotnet build ./SimplCommerce.sln
     displayName: 'dotnet build'
   - script: ./run-tests.sh
     displayName: 'run tests'
   - task: PublishTestResults@2
     displayName: 'Publish Test Results **/*.trx'
     condition: succeededOrFailed()
     inputs:
       testResultsFormat: VSTest
       testResultsFiles: '"**/*.trx'
