trigger:
- master
jobs:
 - job: Build
   pool:
     name: 'Azure Pipelines'
   steps:
   - task: DotNetCoreInstaller@0
     inputs:
       packageType: 'sdk'
       version: '2.2.401'
   - script: echo dotnet build with test files
     displayName: 'dotnet build'
   - script: .echo this can run tests with file
     displayName: 'run tests'
   - task: PublishTestResults@2
     displayName: 'Publish Test Results **/*.trx'
     condition: succeededOrFailed()
     inputs:
       testResultsFormat: VSTest
       testResultsFiles: '"**/*.trx'
