parameters:
    # AdminPassword:defaul******
    # AdminTestPassword: default
    # HostingPlan:default
    # ServerName:default
    # WebsiteName:default
    # azureResourceManagerConnection: '<SERVICE-CONNECTION>' # need service connection
    # subscriptionId: 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' # need Subscription ID
     
stages:
- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      name: Azure Pipelines
      VmImaga: 'latest ubuntu'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'project'
        targetPath: '$(System.ArtifactsDirectory)'

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '<SERVICE-CONNECTION>' # need service connection
        subscriptionId: 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' # need Subscription ID
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'demo-rg'
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.ArtifactsDirectory)/**/FullEnvironmentSetupMerged.json'
        csmParametersFile: '$(System.ArtifactsDirectory)/**/FullEnvironmentSetupMerged.param.json'
        overrideParameters: >- 
          -WebsiteName $(WebsiteName) 
          -PUL_ServerName $(ServerName) 
          -PUL_DBPassword $(AdminPassword) 
          -PUL_DBPasswordForTest $(AdminTestPassword) 
          -PUL_HostingPlanName $(HostingPlan)
        deploymentMode: 'Incremental'
    
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: '<SERVICE-CONNECTION>' # service connection
        appType: 'webApp'
        WebAppName: $(WebsiteName)
        packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'